### ISSUE TITLE
evaluation per epoch

### ISSUE THREAD

**Issue by AI-AUT** [akhilpm/DroneDetectron2#12]
Hello
Although I know this error is not related to the implementation, but after spending too much time I appreciate if help me if you know.
I get this error after 3000 iteration for evaluation per epoch:

 Fast COCO eval is not built. Falling back to official COCO eval.
INFO:croptrain.engine.inference:Start inference on 274 batches
Traceback (most recent call last):
  File "train_net.py", line 94, in <module>
    launch(
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/moghaddami/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/moghaddami/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/moghaddami/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/media/2TB_1/CZDet/DroneDetectron2/train_net.py", line 85, in main
    return trainer.train()
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 156, in train
    self.after_step()
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 190, in after_step
    h.after_step()
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 556, in after_step
    self._do_eval()
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 529, in _do_eval
    results = self._func()
  File "/media/2TB_1/CZDet/DroneDetectron2/croptrain/engine/trainer.py", line 233, in test_and_save_results
    self._last_eval_results = self.test_crop(self.cfg, self.model, self.iter)
  File "/media/2TB_1/CZDet/DroneDetectron2/croptrain/engine/trainer.py", line 277, in test_crop
    results_i = inference_with_crops(model, data_loader, evaluator, cfg, iter)
  File "/media/2TB_1/CZDet/DroneDetectron2/croptrain/engine/inference.py", line 67, in inference_with_crops
    all_outputs = model(inputs, infer_on_crops=True, cfg=cfg)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 885, in forward
    inputs, kwargs = self.to_kwargs(inputs, kwargs, self.device_ids[0])
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 993, in to_kwargs
    kwargs = self._recursive_to(kwargs, device_id) if kwargs else []
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 986, in _recursive_to
    res = to_map(inputs)
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 981, in to_map
    return [type(obj)(i) for i in zip(*map(to_map, obj.items()))]
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 977, in to_map
    return list(zip(*map(to_map, obj)))
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 981, in to_map
    return [type(obj)(i) for i in zip(*map(to_map, obj.items()))]
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 977, in to_map
    return list(zip(*map(to_map, obj)))
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 981, in to_map
    return [type(obj)(i) for i in zip(*map(to_map, obj.items()))]
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 977, in to_map
    return list(zip(*map(to_map, obj)))
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 981, in to_map
    return [type(obj)(i) for i in zip(*map(to_map, obj.items()))]
  File "/home/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 981, in <listcomp>
    return [type(obj)(i) for i in zip(*map(to_map, obj.items()))]
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/yacs/config.py", line 86, in __init__
    init_dict = self._create_config_tree_from_dict(init_dict, key_list)
  File "/media/2TB_1/Miniconda/conda/envs/Detectron2/lib/python3.8/site-packages/yacs/config.py", line 123, in _create_config_tree_from_dict
    for k, v in dic.items():
**AttributeError: 'tuple' object has no attribute 'items'**

**Comment by akhilpm** [comment]
Hmm, it looks like the error is from the cfg object creation. It is coming at this stage when you call eval method due to the lazy executionn of the built-in function ._create_config_tree_from_dict.

I don't have an immediate answer to fix it, because it is not clear to me why it happens.  But I could give certain things I would try to probe it further. First, make sure that the cfg object is created successfully and that it is reading the command line arguments properly in its place. As you already ran the model until a checkpoint is saved (3000 iterations in the code by default), you can use that weights and run the evaluation only for debugging. Check the command line arguments are passed without any mistakes (I suspect this part has the trouble). In eval mode, you can just run without any cmd arguments by putting it all in the YAML file. 

Check in eval mode whether the model is receiving the correct config here: 
File "/media/2TB_1/CZDet/DroneDetectron2/croptrain/engine/inference.py", line 67, in inference_with_crops
all_outputs = model(inputs, infer_on_crops=True, cfg=cfg)

**Comment by zuikeaideren** [comment]
Thank you for your answer. This problem may have occurred after I ran the pycharm software directly connected to the server. After I directly output the running command on the server, it did not report an error.
