### ISSUE TITLE
An error occurred during training

### ISSUE THREAD

**Issue by tdd233** [akhilpm/DroneDetectron2#17]
Thanks for your outstanding work and open source. When I want to re-implement your work, an error occurred shown as below:
*********************************************************************************************************************************************************
[08/17 16:19:02 d2.utils.env]: Using a generated random seed 2905847
Traceback (most recent call last):
  File "train_net.py", line 95, in <module>
    launch(
  File "/media/zz/CCD08CFED08CF04E/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 50, in main
    data_dir = os.path.join(os.environ['SLURM_TMPDIR'], "VisDrone")
  File "/media/zz/CCD08CFED08CF04E/anaconda3/envs/detectron2/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_TMPDIR'
*********************************************************************************************************************************************************
Could you please help me find why the error occurred and how to fix it? Looking forward to your reply!!!

**Comment by akhilpm** [comment]
Line 50 in train_net.py where you get this error is simply setting where your dataset directory is located. If you have carefully read that line, it would have been clear and self-explanatory. The variable name itself is given appropriately as "data_dir". 

Now change this directory to where you actually stored the data in your machine. it will be fixed. Try to fix simple path errors like this on your own.
