### ISSUE TITLE
error while loading images

### ISSUE THREAD

**Issue by AI-AUT** [akhilpm/DroneDetectron2#9]
hello

Im using your implementation for training VisDrone with RCNN-FPN-CROP.yaml config file.
After reading annotation succesfully, I got this error while Im sure my data directory is like you mentioned in your repository.
its just before start to train...........
help me please.
thank you.

Traceback (most recent call last):
  File "train_net.py", line 94, in <module>
    launch(
  File "../Detectron2/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 85, in main
    return trainer.train()
  File "../Detectron2/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "../Detectron2/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "../DroneDetectron2/croptrain/engine/trainer.py", line 135, in run_step
    data = next(self._trainer._data_loader_iter)
  File "../Detectron2/lib/python3.8/site-packages/detectron2/data/common.py", line 291, in __iter__
    for d in self.dataset:
  File "../.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/.local/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "../Detectron2/lib/python3.8/site-packages/detectron2/data/common.py", line 258, in __iter__
    yield self.dataset[idx]
  File "../Detectron2/lib/python3.8/site-packages/detectron2/data/common.py", line 95, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "../Detectron2/lib/python3.8/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "../DroneDetectron2/croptrain/data/dataset_mapper.py", line 62, in __call__
    image = read_image(dataset_dict)
  File "../DroneDetectron2/croptrain/data/detection_utils.py", line 18, in read_image
    if len(image.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'

my dataset directory:
![image](https://github.com/akhilpm/DroneDetectron2/assets/137109895/62f97168-571d-4f8b-813d-0fa35b9beba4)

**Comment by akhilpm** [comment]
This is a silly path-related error, not an issue of this code base. In my train_net.py script, I am using a temp storage location of the HPC cluster we have. 

https://github.com/akhilpm/DroneDetectron2/blob/main/train_net.py#LL49C9-L49C72

You just have to change it to the "data_dir"  to where you store the data.

**Comment by destinational** [comment]
@AI-AUT @akhilpm 
Hello, I have encountered the same problem. I changed the “data_dir”,data_dir = "/home/xxx/Downloads/DroneDetectron2/croptrain/datasets/VisDrone",The files are right here,But the problem hasn't been solved,How did you solve it? Looking forward to your reply.

**Comment by akhilpm** [comment]
To me, this is an issue due to not configuring the dataloader of Pytorch properly. You can check the dataloader documentation or related Stackoverflow questions.

https://pytorch.org/tutorials/beginner/basics/data_tutorial.html
https://stackoverflow.com/questions/59924310/load-custom-data-from-folder-in-dir-pytorch
